HW2: доработка bash-скриптов

diff --git a/parse_users b/parse_users
--- a/parse_users
+++ b/parse_users
@@ -1,5 +1,8 @@
 #!/bin/bash
 
-file="users.txt"
+if ! [ -f "$1" ]; then
+echo "file not found"
+exit
+fi
 
-echo "$(sed '1d' ${file} | awk '{print $3}' | sort | uniq -c | sort -nk1 -r | awk '{print $2}' | head -n 3)"
+echo "$(sed '1d' $1 | awk '{print $3}' | sort | uniq -c | sort -nk1 -r | awk '{print $2}' | head -n 3)"
